export const MyProjects = [
    {
        index: '01',
        imgUrl: '/safariportfolio.png',
        title: 'Typescript and Next.js Portfolio',
        description: `This portfolio website. Built with Typescript, Next.js and Tailwind.`,
        demoLink: '/',
        codeLink: 'https://github.com/Jacob-Clayton/T3-Portfolio',
    },
    {
        index: '02',
        imgUrl: '/safaribridgr.png',
        title: 'Full Stack Website',
        description: `Full Stack Next.js website with integrated APIs. Built with Javascript, Next, React, Node, Express, Tailwind and HTML.`,
        demoLink: 'https://bridgr.xyz',
        codeLink: 'https://github.com/Jacob-Clayton/BRIDGR-Website',
    },
    {
        index: '03',
        imgUrl: '/safarieth.png',
        title: 'Blockchain Analytics',
        description: `Analyse any Ethereum wallet in seconds. An app built with Python using the Numpy, Pandas and Matplotlib packages to analyse blockchain data from multiple Web3 APIs.`,
        demoLink: 'https://jacob-clayton-etherscan-api-app-sblsnb.streamlit.app/',
        codeLink: 'https://github.com/Jacob-Clayton/Ethereum-Analysis',
    },
    {
        index: '04',
        imgUrl: '/safarioldportfolio.png',
        title: 'React.js Portfolio',
        description: `Portfolio website 2023, built with Javascript, React, Framer Motion, CSS, SCSS, HTML, Sanity CMS.`,
        demoLink: '/',
        codeLink: 'https://github.com/Jacob-Clayton/Portfolio',
    },
    {
        index: '05',
        imgUrl: '/safaridex.png',
        title: 'Trading Dashboard',
        description: `Decentralised exchange trading volume dashboard, built on Dune Analytics using SQL based blockchain data.`,
        demoLink: 'https://dune.com/kolsas/dex-volume',
        codeLink: 'https://dune.com/queries/1967725/3250902',
    },
];