export const MyProjects = [
    {
        index: '01',
        imgUrl: '/safariportfolio.png',
        title: 'Typescript and Next.js Portfolio',
        description: `This portfolio website. Built with Typescript, Next.js and Tailwind.`,
        demoLink: '/',
        codeLink: 'https://github.com/Jacob-Clayton/T3-Portfolio',
    },
    {
        index: '02',
        imgUrl: '/safaribridgr.png',
        title: 'Full Stack Next.js Website',
        description: `Full Stack Next.js website with integrated APIs. Built with Javascript, Next, React, Node, Express, Tailwind and HTML.`,
        demoLink: '/',
        codeLink: 'https://github.com/Jacob-Clayton/T3-Portfolio',
    },
    {
        index: '03',
        imgUrl: '/safarieth.png',
        title: 'Ethereum Wallet Analytics App',
        description: `Ethereum analytics app built with Python and the Numpy, Pandas and Matplotlib packages to analyse blockchain data from two APIs.`,
        demoLink: '/',
        codeLink: 'https://github.com/Jacob-Clayton/T3-Portfolio',
    },
    {
        index: '04',
        imgUrl: '/safarioldportfolio.png',
        title: 'React.js Website',
        description: `Portfolio website 2023, built with Javascript, React, Framer Motion, CSS, SCSS, HTML, Sanity CMS.`,
        demoLink: '/',
        codeLink: 'https://github.com/Jacob-Clayton/T3-Portfolio',
    },
    {
        index: '05',
        imgUrl: '/safaridex.png',
        title: 'Ethereum Volume Dashboard',
        description: `Decentralised Exchange vs Aggregator trading volume on Ethereum dashboard, built on Dune Analytics using SQL.`,
        demoLink: '/',
        codeLink: 'https://github.com/Jacob-Clayton/T3-Portfolio',
    },
];