export const MyProjects = [
    {
        index: '01',
        imgUrl: '/safariportfolio.png',
        title: 'Next.js & Typescript Website',
        description: `Portfolio website 2023.`,
        stack: 'Typescript, Next, React, Node, Express, APIs, Tailwind, HTML.',
        demoLink: '/',
        codeLink: 'https://github.com/Jacob-Clayton/T3-Portfolio',
    },
    {
        index: '02',
        imgUrl: '/safaribridgr.png',
        title: 'Next.js & Typescript Website',
        description: `Portfolio website 2023.`,
        stack: 'Javascript, Next, React, Node, Express, APIs, Tailwind, HTML.',
        demoLink: '/',
        codeLink: 'https://github.com/Jacob-Clayton/T3-Portfolio',
    },
    {
        index: '03',
        imgUrl: '/safarieth.png',
        title: 'Ethereum Wallet Analytics App',
        description: `An Ethereum analytics app built with python.`,
        stack: 'Python (Numpy, Pandas, Matplotlib), Web3 APIs.',
        demoLink: '/',
        codeLink: 'https://github.com/Jacob-Clayton/T3-Portfolio',
    },
    {
        index: '04',
        imgUrl: '/safarioldportfolio.png',
        title: 'React.js Website',
        description: `Portfolio website 2023.`,
        stack: 'Python (Numpy, Pandas, Matplotlib), Web3 APIs.',
        demoLink: '/',
        codeLink: 'https://github.com/Jacob-Clayton/T3-Portfolio',
    },
    {
        index: '05',
        imgUrl: '/safarioldportfolio.png',
        title: 'Next.js & Typescript Website',
        description: `Portfolio website 2023.`,
        stack: 'Javascript, React, Framer Motion, CSS, SCSS, HTML, Sanity CMS.',
        demoLink: '/',
        codeLink: 'https://github.com/Jacob-Clayton/T3-Portfolio',
    },
    {
        index: '06',
        imgUrl: '/safarioldportfolio.png',
        title: 'Next.js & Typescript Website',
        description: `Portfolio website 2023.`,
        stack: 'Python (Numpy, Pandas, Matplotlib), Web3 APIs.',
        demoLink: '/',
        codeLink: 'https://github.com/Jacob-Clayton/T3-Portfolio',
    },
];