import { type NextPage } from "next";
import Head from "next/head";
import { Contact, Footer, Hero, Navbar, Projects, Skills } from "components";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Jacob Clayton Portfolio</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Hero />
      <Projects />
      <Skills />
      <Contact />
      <Footer />
    </>
  );
};

export default Home;
