import { type NextPage } from "next";
import Head from "next/head";
import { Navbar, About, Projects, Skills, Contact, Footer } from "components";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Jacob Clayton | Portfolio</title>
        <meta name="Portfolio" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <About />
      <Projects />
      <Skills />
      <Contact />
      <Footer />
    </>
  );
};

export default Home;
